#!/bin/sh

shift $((OPTIND-1))

# $@ = paths
default_umask() {
  find "$@" -type d -print0 | xargs -0 chmod "$(umask -S)" &&
  find "$@" -type f -print0 | xargs -0 chmod "$(umask -S | tr -d 'x')"
}

if [ $# -gt 0 ]
then
  default_umask "$@"
else
  default_umask .
fi
